{{- if .Values.awsCredentials.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "prima-api.fullname" . }}-aws-credentials
  labels:
    {{- include "prima-api.labels" . | nindent 4 }}
type: Opaque
data:
  AWS_ACCESS_KEY_ID: {{ .Values.awsCredentials.accessKeyId | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.awsCredentials.secretAccessKey | b64enc }}
{{- end }}
